---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: label-check
spec:
  description: >-
    Verifies whether an image contains the best practice labels using Conftest.
  params:
    - name: POLICY_DIR
      description: Path to directory containing Conftest policies.
      default: "/project/image/"
    - name: POLICY_NAMESPACE
      description: Namespace for Conftest policy.
      default: "required_checks"
  workspaces:
    - name: workspace
  results:
    - description: Tekton task test output.
      name: HACBS_TEST_OUTPUT
  steps:
    - name: surface-level-checks-required-labels
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)-$(params.POLICY_NAMESPACE)
      env:
        - name: POLICY_NAMESPACE
          value: $(params.POLICY_NAMESPACE)
        - name: POLICY_DIR
          value: $(params.POLICY_DIR)
      securityContext:
        capabilities:
          add:
            - SETFCAP
      script: |
        #!/usr/bin/env bash

        . /utils.sh
        if [ ! -s ../inspect-image/image_inspect.json ]; then
          echo "File $(workspaces.source.path)/hacbs/inspect-image/image_inspect.json did not generate correctly. Check task inspect-image log."
          note="Task $(context.task.name) failed: $(workspaces.source.path)/hacbs/inspect-image/image_inspect.json did not generate correctly. For details, check Tekton task result HACBS_TEST_OUTPUT in task inspect-image."
          HACBS_TEST_OUTPUT=$(make_result_json -r ERROR -t "$note")
          echo "${HACBS_TEST_OUTPUT}" | tee $(results.HACBS_TEST_OUTPUT.path)
          exit 0
        fi

        CONFTEST_OPTIONS=""
        if [ -s "../inspect-image/base_image_inspect.json" ]; then
          CONFTEST_OPTIONS="-d=../inspect-image/base_image_inspect.json"
        fi

        echo "Running conftest using $POLICY_DIR policy, $POLICY_NAMESPACE namespace."
        /usr/bin/conftest test --no-fail ../inspect-image/image_inspect.json "${CONFTEST_OPTIONS}" \
        --policy $POLICY_DIR --namespace $POLICY_NAMESPACE \
        --output=json 2> stderr.txt | tee label_check_output.json

        if [ ! -z $(cat stderr.txt) ]; then
          echo "label-check test encountered the following error:"
          cat stderr.txt
          note="Task $(context.task.name) failed: Command conftest failed. For details, check Tekton task log."
          HACBS_ERROR_OUTPUT=$(make_result_json -r "ERROR" -t "$note")
        fi

        HACBS_TEST_OUTPUT=
        parse_hacbs_test_output $(context.task.name) conftest label_check_output.json || true

        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
