apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stone-soup-build-artifacts-rwo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
