apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "virus, appstudio, hacbs"
  name: clamav-scan
spec:
  description: >-
    Scans the content of container images for viruses, malware, and other malicious content using ClamAV antivirus scanner.
  results:
    - name: HACBS_TEST_OUTPUT
      description: Tekton task test output.
  params:
    - name: image-digest
      description: Image digest to scan.
    - name: image-url
      description: Image URL.
    - name: docker-auth
      description: Folder where container authorization in config.json is stored.

  steps:
    - name: extract-and-scan-image
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      workingDir: /work
      # need to change user since 'oc image extract' requires more privileges when running as root
      # https://bugzilla.redhat.com/show_bug.cgi?id=1969929
      securityContext:
        runAsUser: 1000
      env:
        - name: HOME
          value: /work
        - name: DOCKER_CONFIG
          value: /secrets/registry-auth
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
      resources:
        limits:
          memory: 4Gi
          cpu: '2'
        requests:
          memory: 512Mi
          cpu: 10m
      script: |
        imagewithouttag=$(echo $IMAGE_URL | sed "s/\(.*\):.*/\1/" | tr -d '\n')

        # strip new-line escape symbol from parameter and save it to variable
        imageanddigest=$(echo $imagewithouttag@$IMAGE_DIGEST)

        # check if image is attestation one, skip the clamav scan in such case
        if [[ $imageanddigest == *.att ]]
        then
            echo "$imageanddigest is an attestation image. Skipping ClamAV scan."
            exit 0
        fi
        mkdir content
        cd content
        echo Extracting image.
        if ! oc image extract $imageanddigest; then
          echo "Unable to extract image. Skipping ClamAV scan!"
          exit 0
        fi
        echo Extraction done.
        clamscan -ri --max-scansize=250M | tee /tekton/home/clamscan-result.log
        echo "Executed-on: Scan was executed on version - $(clamscan --version)" | tee -a /tekton/home/clamscan-result.log
      volumeMounts:
        - mountPath: /var/lib/clamav
          name: dbfolder
        - mountPath: /work
          name: work
        - mountPath: /secrets/registry-auth
          name: registry-auth
    - name: modify-clam-output-to-json
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      script: |
        #!/usr/bin/env python3.9
        import json
        import dateutil.parser as parser
        import os

        clamscan_result = "/tekton/home/clamscan-result.log"
        if not os.path.exists(clamscan_result) or os.stat(clamscan_result).st_size == 0:
            print("clamscan-result.log file is empty, so compiled code not extracted. Parsing skipped.")
            exit(0)

        with open(clamscan_result, "r") as file:
            clam_result_str = file.read()

        def clam_result_str_to_json(clam_result_str):

            clam_result_list = clam_result_str.split("\n")
            clam_result_list.remove('')

            results_marker = \
                clam_result_list.index("----------- SCAN SUMMARY -----------")

            hit_list = clam_result_list[:results_marker]
            summary_list = clam_result_list[(results_marker + 1):]

            r_dict = { "hits": hit_list }
            for item in summary_list:
                # in case of blank lines
                if not item:
                    continue
                split_index = [c == ':' for c in item].index(True)
                key = item[:split_index].lower()
                key = key.replace(" ", "_")
                value = item[(split_index + 1):].strip(" ")
                if (key == "start_date" or key == "end_date"):
                  isodate = parser.parse(value)
                  value = isodate.isoformat()
                r_dict[key] = value
            print(json.dumps(r_dict))
            with open('/tekton/home/clamscan-result.json', 'w') as f:
              print(json.dumps(r_dict), file=f)

        def main():
            clam_result_str_to_json(clam_result_str)

        if __name__ == "__main__":
            main()
    - name: store-hacbs-test-output-result
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      script: |
        #!/usr/bin/env bash
        source /utils.sh

        if [ -f /tekton/home/clamscan-result.json ];
        then
          cat /tekton/home/clamscan-result.json
          INFECTED_FILES=$(jq -r '.infected_files' /tekton/home/clamscan-result.json || true )
          if [ -z "${INFECTED_FILES}" ]; then
            echo "Failed to get number of infected files."
            note="Task $(context.task.name) failed: Unable to get number of infected files from /tekton/home/clamscan-result.json. For details, check Tekton task log."
          else
            if [[ "${INFECTED_FILES}" -gt 0 ]]; then RES="FAILURE"; else RES="SUCCESS"; fi
            note="Task $(context.task.name) completed: Check result for antivirus scan result."
            HACBS_TEST_OUTPUT=$(make_result_json -r "${RES}" -s 1 -f "${INFECTED_FILES}" -t "$note")
          fi
        else
          note="Task $(context.task.name) failed: /tekton/home/clamscan-result.json doesn't exist. For details, check Tekton task log."
        fi

        HACBS_ERROR_OUTPUT=$(make_result_json -r "ERROR" -t "$note")
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
  # sidecar is rebuilt daily(is meant to be updated daily), hence the usage of the tag instead of digest
  # provides latest virus database for clamscan only
  # does not execute anything
  sidecars:
    - image: quay.io/redhat-appstudio/clamav-db:latest  # explicit floating tag, daily updates
      imagePullPolicy: Always
      name: database
      script: |
        #!/usr/bin/env bash
        clamscan --version
        cp -r /var/lib/clamav/* /tmp/clamdb
      volumeMounts:
        - mountPath: /tmp/clamdb
          name: dbfolder
  volumes:
    - name: dbfolder
      emptyDir: {}
    - name: work
      emptyDir: {}
    - name: registry-auth
      secret:
        secretName: $(params.docker-auth)
        optional: true
