apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: sast-snyk-check
spec:
  description: >-
    Scans source code for security vulnerabilities, including common issues such as SQL injection, cross-site scripting (XSS), and code injection attacks using Snyk Code, a Static Application Security Testing (SAST) tool.
  results:
    - description: Tekton task test output.
      name: HACBS_TEST_OUTPUT
  params:
    - name: SNYK_SECRET
      description: Name of secret which contains Snyk token.
      default: ""
    - name: ARGS
      type: string
      description: Append arguments.
      default: "--all-projects --exclude=test*,vendor,deps"
  volumes:
    - name: snyk-secret
      secret:
        secretName: $(params.SNYK_SECRET)
        optional: true
  steps:
    - name: sast-snyk-check
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      volumeMounts:
        - name: snyk-secret
          mountPath: "/etc/secrets"
          readOnly: true
      env:
        - name: SNYK_SECRET
          value: $(params.SNYK_SECRET)
        - name: ARGS
          value: $(params.ARGS)
      script: |
        #!/usr/bin/env bash
        . /utils.sh
        SNYK_TOKEN="$(cat /etc/secrets/snyk_token)"
        if [[ -z $SNYK_TOKEN ]]; then
          echo "SNYK_TOKEN not defined. Create $SNYK_SECRET secret with key containing Snyk token." | tee stdout.txt
          note="Task $(context.task.name) skipped: SNYK_TOKEN is empty."
          HACBS_TEST_OUTPUT=$(make_result_json -r SKIPPED -t "$note")
          exit 0
        fi
        export SNYK_TOKEN
        SNYK_EXIT_CODE=0
        snyk code test $ARGS ../.. --sarif-file-output=sast_snyk_check_out.json 1>&2>> stdout.txt || SNYK_EXIT_CODE=$?
        test_not_skipped=0
        SKIP_MSG="We found 0 supported files"
        grep -q "$SKIP_MSG" stdout.txt || test_not_skipped=$?

        if [[ "$SNYK_EXIT_CODE" -eq 0 ]] || [[ "$SNYK_EXIT_CODE" -eq 1 ]]; then
          cat sast_snyk_check_out.json
          HACBS_TEST_OUTPUT=
          parse_hacbs_test_output $(context.task.name) sarif sast_snyk_check_out.json  || true

        # When the test is skipped, the "SNYK_EXIT_CODE" is 3 and it can also be 3 in some other situation
        elif [[ "$test_not_skipped" -eq 0 ]]; then
          note="Task $(context.task.name) skipped: Snyk code test found zero supported files."
          HACBS_ERROR_OUTPUT=$(make_result_json -r SKIPPED -t "$note")
        else
          echo "sast-snyk-check test failed because of the following issues:"
          cat stdout.txt
          note="Task $(context.task.name) failed: For details, check Tekton task log."
          HACBS_ERROR_OUTPUT=$(make_result_json -r ERROR -t "$note")
        fi
        echo "${HACBS_TEST_OUTPUT:-${HACBS_ERROR_OUTPUT}}" | tee $(results.HACBS_TEST_OUTPUT.path)
  workspaces:
  - name: workspace
