{{- range .Values.bluegreen }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $.Chart.Name }}-{{ .name }}
  name: {{ $.Chart.Name }}-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: {{ $.Values.route.targetPort }}
  to:
    kind: {{ $.Values.route.kind }}
    name:  {{ $.Chart.Name }}-{{ .name }}
    weight: {{ $.Values.route.weight }}
  wildcardPolicy: {{ $.Values.route.wildcardPolicy | default "None" }}
{{- end }}