{{- if not (eq .Values.enabled "plumbing") }}
{{- range .Values.clusterGroup.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
  name: {{ . }}
spec:
---
{{- end }}
{{- end }}
