apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pipeline
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostIPC: true
allowHostPID: true
allowHostPorts: true
readOnlyRootFilesystem: true
allowHostNetwork: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.stoneSoupPipeline.serviceAccount }}
