apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: fbc-related-image-check
spec:
  description: >-
    Checks the validity of all the images referenced in the file-based catalog (FBC) to inspect manifest content using Skopeo.
  results:
    - name: HACBS_TEST_OUTPUT
      description: Tekton task test output.
  workspaces:
    - name: workspace
  steps:
    - name: check-related-images
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.12@sha256:8c833349cad40d34262548295cd4eb1bd330e42fbb221ef54e6caee15ae1d208
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      resources:
        limits:
          memory: 4Gi
          cpu: '2'
        requests:
          memory: 512Mi
          cpu: 10m
      script: |
        #!/usr/bin/env bash
        set -o pipefail
        source /utils.sh
        FAILEDIMAGES=""
        catalog="$(find $(workspaces.workspace.path)/hacbs/fbc-validation/ -name catalog.yaml)"

        # OPM generates catalog file in a way that yaml file could contain stream of JSON objects
        # thats why we need jq in for this situation, because yq can't parse this file
        # however there is also posibility that catalog.yaml has yaml data in it

        relImgs="$(yq -r '.relatedImages[]?.image' $catalog)"
        if [ $? -ne 0 ]; then
          echo "Processing the catalog with yq failed because catalog.yaml contains data type other than yaml. Attempting to process with jq..."
          relImgs="$(jq -r '.relatedImages[]?.image' $catalog)"
          if [ $? -ne 0 ]; then
            echo "Could not get related images. Make sure catalog.yaml exists in FBC fragment image and it is valid .yaml format."
            note="Task $(context.task.name) failed: Could not fetch related images. Make sure you have catalog.yaml formatted correctly in your file-based catalog (FBC) fragment image."
            HACBS_TEST_OUTPUT=$(make_result_json -r FAILURE -f 1 -t "$note")
            echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
          exit 0
          fi
        fi

        echo -e "These are related images:\n$relImgs."
        # cycle through those related images and show outputs
        for i in ${relImgs// /}
        do
          if ! skopeo inspect --no-tags "docker://${i}"; then
            echo "Skopeo inspect failed on related image: $i."
            FAILEDIMAGES+="$i, "
          fi
        done
        if [ -z "$FAILEDIMAGES" ]; then
          note="Task $(context.task.name) succeeded: For details, check Tekton task result HACBS_TEST_OUTPUT."
          HACBS_TEST_OUTPUT=$(make_result_json -r SUCCESS -s 1 -t "$note")
          echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
        else
          echo "These images failed inspection: $FAILEDIMAGES."
          note="Task $(context.task.name) failed: Command skopeo inspect could not inspect images. For details, check Tekton task log."
          HACBS_TEST_OUTPUT=$(make_result_json -r FAILURE -f 1 -t "$note")
          echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
          exit 0
        fi
